apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-template
  template:
    metadata:
      labels:
        app: microservice-template
    spec:
      containers:
        - name: microservice-template
          image: microservice-template:dev
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
