apiVersion: v1
kind: Service
metadata:
  name: microservice-template-service
spec:
  type: NodePort
  selector:
    app: microservice-template
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
